### PR TITLE
Armor&Tool Auto Prof

### PR DESCRIPTION
**Pull request by szefo09**
PR that addresses Issue #7 
Feel free to edit is however you want
Allow edits by maintainers is on.

### CODE REVIEW

**Comment by trioderegion** [comment]
Initial changes look good. Pulling into test branch.

**Comment by szefo09** [comment]
Before commiting to master, I guess changing multiple ifs in the hook into a switch case would look better.

**Comment by kandashi** [comment]
The current system for marking Tools as proficient isnt quite working as indended. Tools have a 0, 0.5, 1, 2 system of marking proficiency, different to the armour/weapons boolean check.

**Comment by szefo09** [comment]
> The current system for marking Tools as proficient isnt quite working as indended. Tools have a 0, 0.5, 1, 2 system of marking proficiency, different to the armour/weapons boolean check.

Got it.
So instead of true, the tool proficiency should set the value to 1.
 `actor.updateOwnedItem({ _id: item._id, "data.proficient": 1 });`

**Pull request merged**
