### PR TITLE
MIT Licensing

### PR DESCRIPTION
**Pull request by trioderegion**
Initial steps on properly licensing dnd5e-helpers.

### CODE REVIEW

**Comment by trioderegion** [comment]
It has always been my intention for DnD5e Helpers to be used freely and for contributors to be recognized. As the team and code-base grows, it is important to finally establish this properly.

As such, the DnD5e Helpers team has decided to formally license this work under the [MIT License](https://mit-license.org/).

### Respecting Your Rights As Contributors
* As a contributor, your work is highly valued and appreciated and we want to recognize this more formally.
* If you have questions about this change, feel free to DM me directly on Discord (@honeybadger#2614) or email (matt.haentschke@gmail.com)

### How This Works
1. This pull request contains the licensing work in progress
2. I have populated the CONTRIBUTORS.md file with the listed github names of all contributors.
3. Please reply to this pull request with your preferred attribution name (if different from github name) and contact email. If a contact email is not provided, we will use `<username>@users.noreply.github.com`.
4. Please approve the pull request. If you have a concern, do not write it in your approval to avoid confusion.
5. Once every contributor has approved the change, we will merge it to the repo.

### Impact Analysis
As we are moving from All Rights Reserved (no license) to a very permissive license (MIT), the assumption is that this will be agreeable for all involved as we are effectively giving rights back to the community for use and re-use. If this re-licensing is *not* agreeable for any particular contributor, we will take needed steps to remove those contributions from our code base such that we can release it freely under MIT.

**Comment by trioderegion** [comment]
Contributor feedback requested from:
@szefo09 , @BrotherSharper , @drdwing , @MS-PBS , @brnmuller , @vtt-lair , @xdy

**Comment by szefo09** [comment]
Approved.

**Comment by MS-PBS** [comment]
Hey, I just did some translations, that's nothing compared to all the work you guys have put into this module. Please go ahead with this. I will keep on translating.

**Comment by xdy** [comment]
Fine with me, I approve!

**Comment by drdwing** [comment]
Oh, of course! 👌

**Comment by vtt-lair** [comment]
Is cool, approved

**Review by kandashi — APPROVED** [review]
All good :)

**Comment by brnmuller** [comment]
Of course, all good! :)

**Comment by BrotherSharper** [comment]
Sorry for being late!
I approve and this approval is on behalf of `Touge` who provided the localization file to the Japanese community

**Pull request merged**
